name: mirror-images

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  mirror:
    name: mirror
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: imjasonh/setup-crane@v0.3
      - name: Mirror
        run: |
          #!/bin/bash
          set -e -x

          for i in $(<images.txt); do
              crane copy $i ghcr.io/sans-sroc/images-mirror/$i
          done
